Fe documentation
umberto-fontanazza/kiruna-explorer pull request #143
Opened 2024-11-30 19:55 UTC by stysh98

UI Documentation for Handling Documents in the Same Spot

2024-11-30 20:09 UTC, emanuelefrisi commented on server/test/TEstauth.test.ts
> +    await Database.reset();
Database.reset() is not an existent method

2024-11-30 20:10 UTC, emanuelefrisi commented on server/test/TEstauth.test.ts
> +    // Ensure the database is in a clean state
Can we remove chatgpt-like comments?

2024-11-30 20:13 UTC, emanuelefrisi commented on UI Doc.md
Can you design the figma interface for this UI documentation?

2024-11-30 20:14 UTC, emanuelefrisi requested changes
Read the comments

2024-11-30 21:42 UTC, michepaolo approved these changes

2024-12-01 17:19 UTC, emanuelefrisi commented on server/test/TEstauth.test.ts
Why did you deleted them?

2024-12-01 17:19 UTC, emanuelefrisi approved these changes
Ok

2024-12-01 17:20 UTC, merged